### ISSUE TITLE
where is the change.sh

### ISSUE THREAD

**Issue by pagict** [wujingbang/aodv-Android#1]
在你的README中提到了用 /system/change.sh 来修改设备名称，但是在给出的文件中似乎并没有该文件。能帮忙提供么？

**Comment by pagict** [comment]
此外，在android的 adb 中，提示没有iw命令，不知道是什么情况    FYI，i'm a newbie,   Thx in advance  :-)

**Comment by wujingbang** [comment]
你好，readme中下半部分（中文）是由其他组员加入的配置说明，是针对我们的实验环境的。对你来说你只需要看前半部分编译出ko文件，再根据adhoc-config.sh加载模块就能运行。该aodv代码中加入了较多特殊的功能，都是正常情况下用不到的，如果要看源码，建议看最初版本。
iw是一个单独的配置程序，和iwconfig功能类似，在不同的环境中不一定两个都好用，你可以上网查一下。下载源码后自行编译iw

**Comment by pagict** [comment]
最初版本是针对2.X的内核，我现在想把这个协议移植到Android上来，所以找到了你啦~

或者你有哪个commit 版本是仅做了内核移植没有添加新功能的么？我找了一下，似乎没有找到相关的commit。

如果可以，我的邮箱是 pagict#[at]gmail.com

**Comment by wujingbang** [comment]
0a5c27e应当是最早可以运行的。

**Comment by JAYANTH123** [comment]
https://github.com/wujingbang/aodv-uu

2015-10-05 20:31 GMT-07:00 pagict notifications@github.com:
